name: CI-Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build and test
      run: cd Essential_Feed && xcodebuild clean build test -project Essential_Feed.xcodeproj -scheme CI CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
    - name: Build and test
      run: cd Essential_Feed && xcodebuild clean build test -project Essential_Feed.xcodeproj -scheme CI_iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 8" 
